// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ResumeProject.Data;
using System;

namespace ResumeProject.Migrations
{
    [DbContext(typeof(ResumeContext))]
    [Migration("20190321004457_changed-phone-number-again")]
    partial class changedphonenumberagain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ResumeProject.Models.Conference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventType");

                    b.Property<int>("PersonID");

                    b.Property<string>("Role");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Conference");
                });

            modelBuilder.Entity("ResumeProject.Models.Description", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Duties");

                    b.Property<int>("ExperienceID");

                    b.HasKey("ID");

                    b.HasIndex("ExperienceID");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("ResumeProject.Models.Education", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Degree");

                    b.Property<DateTime>("GraduationDate");

                    b.Property<int>("PersonID");

                    b.Property<string>("School");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("ResumeProject.Models.Experience", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CurrentlyStillWorking");

                    b.Property<string>("ExperienceType");

                    b.Property<string>("Organization");

                    b.Property<int>("PersonID");

                    b.Property<string>("Role");

                    b.Property<int>("YearsService");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("ResumeProject.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<long>("PhoneNumber");

                    b.HasKey("ID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ResumeProject.Models.PersonalSkill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PersonID");

                    b.Property<string>("Skill");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonalSkill");
                });

            modelBuilder.Entity("ResumeProject.Models.Conference", b =>
                {
                    b.HasOne("ResumeProject.Models.Person", "People")
                        .WithMany("Events")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ResumeProject.Models.Description", b =>
                {
                    b.HasOne("ResumeProject.Models.Experience", "Experiences")
                        .WithMany("Descriptions")
                        .HasForeignKey("ExperienceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ResumeProject.Models.Education", b =>
                {
                    b.HasOne("ResumeProject.Models.Person", "People")
                        .WithMany("Educations")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ResumeProject.Models.Experience", b =>
                {
                    b.HasOne("ResumeProject.Models.Person", "People")
                        .WithMany("Experiences")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ResumeProject.Models.PersonalSkill", b =>
                {
                    b.HasOne("ResumeProject.Models.Person", "People")
                        .WithMany("PersonalSkills")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
